<<<<<<< HEAD
#ifndef INCLUDED_CYDISABLEDSHEETS_H
#define INCLUDED_CYDISABLEDSHEETS_H

#define DAC__DISABLED 1u /* DAC */
#define LCD__DISABLED 1u /* LCD */

#endif /* INCLUDED_CYDISABLEDSHEETS_H */
=======
#ifndef INCLUDED_CYDISABLEDSHEETS_H
#define INCLUDED_CYDISABLEDSHEETS_H

#define DAC__DISABLED 1u /* DAC */
#define LCD__DISABLED 1u /* LCD */

#endif /* INCLUDED_CYDISABLEDSHEETS_H */
>>>>>>> remotes/origin/master
